@api = http://localhost:5000

POST {{api}}/usuario/creaUsuarioAlumno
Content-Type: application/json

        {
            "codigo":"20190559I",
            "nombre": "Sebastian",
            "apellido": "Seg",
            "email": "sebas@uni.pe",
            "clave": "1234"
        }

###

POST {{api}}/usuario/iniciaSesionAlumno
Content-Type: application/json

        {
            "codigo": "20170382F",
            "clave": "1234"
        }

###